# Question 1

In [44]:
import numpy as np

# Question 2

In [45]:
arr = np.arange(2,51,3)
print(arr)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47 50]


In [19]:
a = []
b = []
print("Enter elements for first list")
for i in range(5):
    a.append(int(input()))

print("Enter elements for second list")
for i in range(5):
    b.append(int(input()))

# convert to numpy array
arr1 = np.array(a)
arr2 = np.array(b)

#concat and sort two lists
result = np.concatenate((arr1,arr2))
print(result)
res = np.sort(result)
print(res)

Enter elements for first list
12
2
6
71
6
Enter elements for second list
09
8
33
12
4
[12  2  6 71  6  9  8 33 12  4]
[ 2  4  6  6  8  9 12 12 33 71]


# Question 3

In [26]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15]])
print(arr)
# dimensions of array
print(arr.shape)
#size of array
print(arr.size)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]
(5, 3)
15


# Question 4

In [41]:
arr = np.arange(5)
print(arr.shape)
print(arr)
print()
# convert 1D array to a 2D array using np.newaxis
arr_2D = arr[np.newaxis] 
  
print(arr_2D.shape)
print(arr_2D)
print()

# convert 1D array to a 2D array using np.expand_dims
y = np.expand_dims(arr, axis=1)
print(y)
print(y.shape)

(5,)
[0 1 2 3 4]

(1, 5)
[[0 1 2 3 4]]

[[0]
 [1]
 [2]
 [3]
 [4]]
(5, 1)
